### ISSUE TITLE
Windows functionality

### ISSUE THREAD

**Issue by Emilcrafter** [loganwilliams/spacelapser#2]
Tried for hours installing this on Windows (inexperienced). The readme instructions do not work for pleb windows. I have npm installed. "make" command was not installed natively, npm make command does not work. Makefile command in gitbash at ./spacelapser returns that none of the commands in npm makefile were found. this project looked really cool so I hope someone will help.

**Comment by alexsouta** [comment]
Having the same issue as Emilcrafter, would love to play around with this but am unable to get it to work on my Windows machine.
Any assistance would be greatly appreciated!

**Comment by loganwilliams** [comment]
Thanks for reporting this! I don't have a Windows machine to use for testing this, so I haven't been able to set up the build properly for Windows.

This is a C++/OpenFrameworks based application, not a JavaScript thing, so it doesn't need node. Instead, you should install OpenFrameworks and follow these directions for creating a new project: https://openframeworks.cc/setup/vs/. Then, load up the source code from this project. If this works, could you share the project configuration files in a fork of this project?

Thanks!
Logan

**Comment by Emilcrafter** [comment]
Thank you for responding. I set up a VM running the latest Ubuntu build on my Windows machine. Even though I followed your instructions, I had several errors which I had to bypass. However, after McGyvering a solution, the make command still can't find OF-native resources that obviously exist. Did you make this on OSX? I will try installing openframeworks on Windows using the link you provided. Hopefully it will work. I'll get back to you.

**Comment by Emilcrafter** [comment]
After trying the very vague solution for building OF projects on Windows, the misleading documentation and counter intuitive errors have sprung a newfound confidence in me; that I am not the right person to try and compile this. I might continue my trials with the Ubuntu VM, but so far I haven't gotten much luck.

**Comment by loganwilliams** [comment]
@Emilcrafter If you have access to a Mac OS computer, I published a binary that you can just download and run. Sorry again for the trouble you had compiling this, and thanks for the efforts.
