### ISSUE TITLE
Poco/condition.h not found

### ISSUE THREAD

**Issue by JFtechOfficial** [loganwilliams/spacelapser#3]
Hi, I followed the instructions to run spacelapser, but when I try to build it returns the error you can see in the screenshot about Poco/condition.h not being found. I tried some OF examples, they work fine. Even the empty example, which is located in the 'myApps' folder (like the spacelapser folder), builds successfully. I got the same error on Ubuntu.
![Image 2020-02-16 at 11 20 31](https://user-images.githubusercontent.com/36900161/74603754-20ef1c80-50b7-11ea-86bb-8c5523142e95.jpeg)

**Comment by loganwilliams** [comment]
@JFtechOfficial Can you reproduce with the latest version? I tweaked it a bit to work on Big Sur and a new machine of mine. This also resulted in `ofxPoco` being added to `addons.make`, which might make a difference when including dependencies?

If all else fails, I also uploaded a binary release that you should be able to just download and run.
